In [26]:
import numpy as np 
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


# Methods or Functions of Numpy


In [34]:
import numpy as np
b = np.zeros((2,3))
c = np.ones((3,3))
d = np.full((4,3), 6.789)

np.random.seed(42)
e = np.random.random((3,4))

f = np.eye(5)
print(a,b,c,d,e,f,sep ="\n\n")

[[1 2 3 4]
 [5 6 7 8]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[6.789 6.789 6.789]
 [6.789 6.789 6.789]
 [6.789 6.789 6.789]
 [6.789 6.789 6.789]]

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Attributes of Numpy array

In [23]:
print(a)
print(a.dtype.name)
print(a.size)
print(a.ndim)
print(a.shape)
print(a.itemsize)
print(b.itemsize)

[[1 2 3 4]
 [5 6 7 8]]
int64
8
2
(2, 4)
8


In [44]:
print(e)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]


In [45]:
print(e[2,2])
print(e[0:2,0:2])

0.020584494295802447
[[0.37454012 0.95071431]
 [0.15601864 0.15599452]]


# Modifying Elements in array

In [46]:
e[0,2] = 8.9888
print(e)

[[0.37454012 0.95071431 8.9888     0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]


In [47]:
e [0:2, 0:2] = 10.001
print(e)

[[10.001      10.001       8.9888      0.59865848]
 [10.001      10.001       0.05808361  0.86617615]
 [ 0.60111501  0.70807258  0.02058449  0.96990985]]


In [1]:
print("Hello

world")


Helloworld
